In [1]:
import numpy as np

b = np.array([2, 4, 6, 8])
b

array([2, 4, 6, 8])

In [2]:
print(b)

[2 4 6 8]


In [3]:
b.ndim

1

In [4]:
b.size

4

In [5]:
b.shape

(4,)

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
a.ndim

1

In [14]:
a.shape

(10,)

In [15]:
a.size

10

In [19]:
import numpy as np

a = np.arange(7, 11)
a

array([ 7,  8,  9, 10])

In [21]:
import numpy as np

a = np.arange(7, 11, 2)
a

array([7, 9])

In [23]:
import numpy as np

f = np.arange(2.0, 9.8, 0.3)
f

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6,
       5.9, 6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. , 8.3, 8.6, 8.9, 9.2, 9.5,
       9.8])

In [27]:
import numpy as np

g = np.arange(10, 4, -1.5, dtype=float)
g

array([10. ,  8.5,  7. ,  5.5])

In [28]:
import numpy as np

a = np.zeros((3,))
a

array([0., 0., 0.])

In [29]:
a.ndim

1

In [30]:
a.shape

(3,)

In [31]:
a.size

3

In [32]:
import numpy as np

k = np.ones((3, 5))
k

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
import numpy as np

b = np.zeros((2, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
b.ndim

2

In [35]:
b.shape

(2, 4)

In [36]:
b.size

8

In [37]:
import numpy as np

m = np.random.random((3, 5))
m

array([[0.39431413, 0.18974499, 0.31503716, 0.06800432, 0.5376019 ],
       [0.19000352, 0.14459449, 0.48458843, 0.59685164, 0.92958743],
       [0.29146366, 0.65103364, 0.10881146, 0.48624446, 0.52384846]])

In [38]:
import numpy as np

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a = a.reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
a.ndim

2

In [41]:
a.shape

(2, 5)

In [42]:
a.size

10

In [43]:
a = a.reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
a.ndim

2

In [45]:
a.shape

(5, 2)

In [46]:
a.size

10

In [47]:
a.shape = (2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
a = a.reshape(3, 4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [49]:
a = np.arange(10)
a[7]

7

In [50]:
a[-1]

9

In [51]:
a.shape = (2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
a[1, 2]

7

In [53]:
l = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
l

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [54]:
l[1, 2]

TypeError: list indices must be integers or slices, not tuple

In [55]:
l(1, 2)

TypeError: 'list' object is not callable

In [56]:
l[1][2]

7

In [57]:
a = np.arange(10)
a = a.reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
a[0, 2:]

array([2, 3, 4])

In [59]:
a[-1, :3]

array([5, 6, 7])

In [60]:
a[:, 2:4] = 1000
a

array([[   0,    1, 1000, 1000,    4],
       [   5,    6, 1000, 1000,    9]])

In [61]:
from numpy import *

a = arange(4)
a

array([0, 1, 2, 3])

In [62]:
a *= 3

In [63]:
a

array([0, 3, 6, 9])

In [64]:
plain_list = list(range(4))
plain_list

[0, 1, 2, 3]

In [65]:
plain_list = [num * 3 for num in plain_list]
plain_list

[0, 3, 6, 9]

In [66]:
from numpy import *
a = zeros((2,5)) + 17.0
a

array([[17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.]])

In [68]:
import numpy as np
coefficients = np.array([[4,5], [1,2]])
dependents = np.array([20, 13])
answers = np.linalg.solve(coefficients, dependents)
answers

array([-8.33333333, 10.66666667])

In [69]:
4 * answers[0] + 5 * answers[1]

20.0

In [70]:
1 * answers[0] + 2 * answers[1]

13.0

In [71]:
product = np.dot(coefficients, answers)
product

array([20., 13.])

In [72]:
np.allclose(product, dependents)

True